### ISSUE TITLE
Contao 4 freigabe wann möglich?

### ISSUE THREAD

**Issue by csaeum** [1up-lab/contao-efg#5]

**Comment by bytehead** [comment]
Wie bereits in [Important Note 2](https://github.com/1up-lab/contao-efg#important-note-2) erwähnt, kriegt dieses Repo keine Updates. 
Es ist nur als Packagist-Mirror für alte Projekte gedacht. 
Es wäre sowieso besser wenn du [contao-leads](https://github.com/terminal42/contao-leads) verwenden würdest 🙂
